/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/scene1.ts" />
/// <reference path="../scenes/scene2_1.ts" />
/// <reference path="../scenes/scene2_2.ts" />
/// <reference path="../scenes/scene3_1.ts" />
/// <reference path="../scenes/scene3_2.ts" />
/// <reference path="../scenes/scene3_3.ts" />
/// <reference path="../scenes/scene3_4.ts" />
/// <reference path="../scenes/scene4_1.ts" />
/// <reference path="../scenes/scene4_2.ts" />
/// <reference path="../scenes/scene4_3.ts" />
/// <reference path="../scenes/scene4_4.ts" />
/// <reference path="../scenes/scene4_5.ts" />
/// <reference path="../scenes/scene4_6.ts" />
/// <reference path="../scenes/scene4_7.ts" />
/// <reference path="../scenes/scene4_8.ts" /> 
//# sourceMappingURL=_reference.js.map